#!/usr/bin/env bash
# write I'm alive for every 2 sec


trap "sudo rm /var/run/my_process.pid" SIGINT
trap "sudo rm /var/run/my_process.pid" SIGINT


while true;
do
    sudo sh -c 'echo "I am alive!" >> /tmp/my_process' 
done
