#!/usr/bin/env bash

sudo apt install ufw
sudo ufw disable
sudo ufw reset
sudo ufw default allow outgoing
sudo ufw default deny incomming
sudo ufw allow 80
sudo ufw allow 443
sudo ufw allow 22
sudo ufw enable
