#!/usr/bin/env bash
# changing the localhost ip and facebook ip

cp /etc/hosts ~/hosts.new
sed -i '/localhost/d' ~/hosts.new
printf "127.0.0.2\tlocalhost\n" >> ~/hosts.new
sed -i '/facebook/d' ~/hosts.new
printf "8.8.8.8\tfacebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
