#!/usr/bin/env bash
# changing the localhost ip and facebook ip

cp /etc/hosts ~/hosts.new
sed -i '/localhost/d' /etc/hosts
printf "127.0.0.2\tlocalhost" >> /etc/hosts
sed -i '/facebook/d' /etc/hosts
printf "8.8.8.8\tfacebook.com" >> /etc/hosts
cp -f ~/hosts.new /etc/hosts
