#!/usr/bin/env bash
#this script is to run nginx as nginx user not root

sudo apt update
sudo apt install -y nginx 
sudo systemctl start nginx
sudo sed -i s/'http* {'/'http {\n\tuser nginx;'/ /etc/nginx/nginx.conf
sudo sed -i s/'listen*\s80;'/'listen 8080;'/ /etc/nginx/nginx.conf
sudo systemctl restart nginx
