#!/usr/bin/env bash
#this script is to run nginx as nginx user not root

sudo apt update
sudo apt install -y nginx 
sudo systemctl start nginx
sudo useradd -r nginx
sudo sed -i s/'user www-data'/'user nginx;'/ /etc/nginx/nginx.conf
sudo sed -i s/'listen*\s80;'/'listen 8080;'/ /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /var/log/nginx
sudo chown -R nginx:nginx /etc/nginx
sudo -u nginx service nginx restart
