#!/usr/bin/env bash
#fix it short and sweet
sudo useradd -r nginx
sudo sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod u+xr o+r g+r /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx restart
